import express, { Request, Response, NextFunction } from 'express';
import examController from '../controller/ExamController';
import authenticateJWT from '../middleware/auth';
const router = express.Router();
router.get('/', examController.list);
router.get('/teacher',authenticateJWT,examController.list);
router.get('/:id', examController.get);
router.post('/',authenticateJWT,examController.post);
router.put('/:id',examController.put);
router.delete('/:id', examController.remove);
export default router;
