import express from 'express';
import authenticateJWT from './../middleware/auth';
import homeworkController from '../controller/HomeworkController';
const router = express.Router();
router.get('/',homeworkController.list);
router.get('/teacher',authenticateJWT,homeworkController.list);
router.get('/:id', homeworkController.get);
router.post('/',authenticateJWT,homeworkController.post);
router.put('/:id',homeworkController.put);
router.delete('/:id', homeworkController.remove);
export default router;
